- hosts: all
  gather_facts: no
  vars:
    ghc_version: "7.10.3"

  tasks:
  - block:
    - apt_repository: repo=ppa:hvr/ghc
    - apt: name=ghc-{{ghc_version}}
    - lineinfile:
        dest: /home/vagrant/.bashrc
        create: yes
        line: export PATH="$HOME/.cabal/bin:/opt/ghc/{{ghc_version}}/bin:$PATH"
    become: yes

  - block:
    - apt_key: keyserver=keyserver.ubuntu.com id=575159689BEFB442
    - apt_repository: repo='deb http://download.fpcomplete.com/ubuntu wily main'
    - apt: name=stack
    - lineinfile:
        dest: /home/vagrant/.bashrc
        create: yes
        line: export PATH="$HOME/.local/bin:$PATH"
    become: yes

  - lineinfile:
      dest: /home/vagrant/.bashrc
      create: yes
      line: cd /vagrant
    become: yes

  - apt: name={{item}}
    with_items:
      - build-essential
      - zlib1g-dev
      - libmysqlclient-dev
      - libpq-dev
    become: yes
